# Generated by Django 4.0.1 on 2023-05-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customer_type_of'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='no_of_Rooms',
        ),
    ]
