# Generated by Django 4.2.2 on 2023-06-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_quantity_product_no_of_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='no_of_Rooms',
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
